### PR TITLE
Enh/dynamic reports

### PR DESCRIPTION
**Pull request by eurunuela**
The dynamic part of the reports is almost done now. The linking of the time series and spectrum plots with the rest is the only thing missing.

### CODE REVIEW

**Comment by emdupre** [comment]
This is great, thanks !!! Just confirming: were you thinking to link both the dynamic and static time series ?

**Comment by eurunuela** [comment]
No, I was trying to link the kappa and rho figures with their respective time series and spectrum. I’m talking about [this line](https://github.com/eurunuela/tedana/blob/8a8fe7e2c68a0d90e2e6092b469343b4b5adcdda/tedana/reporting/html_report.py#L151).

**Comment by emdupre** [comment]
Yes, sorry, I think I'm just confused as `ts_plot, fft_plot` are both the Bokeh plots as far as I understood, and I thought we were re-linking in the static figures (which include the static TS and FFT plots. But please let me know what you're thinking !

**Comment by eurunuela** [comment]
Well, I’ve to understand what’s going on in that line. More specifically, what each input argument should be to make them work with the JS. 

Any help appreciated!

**Comment by emdupre** [comment]
Just fetched your branch :)

**Comment by emdupre** [comment]
OK, I merged your commits in ! For now I've removed the dynamic TS and FFT plots -- you can see what it looks like in the attached:

Screenshot_2020-04-13 Tedana report

We should definitely keep iterating on this. But thanks so much :tada: :tada: !

**Comment by emdupre** [comment]
To (hopefully) address your previous concern -- that line was supposed to be a one time call to each generated Bokeh figure to link them with the right tap_callback. The reason the outputs weren't displaying (at least for me) was that the `unescape` calls on the HTML were actually being too aggressive and commenting out the correct input. Removing them fixed up the code and now it runs correctly (at least on my machine !).

**Comment by eurunuela** [comment]
Oh, so it was the unescape that made it fail... I was starting to go a bit crazy with the linking. I knew the rest worked.

So, is the idea to have the static ones below? Where do we go from here?

**Pull request merged**
