### PR TITLE
[FIX] Fix errors in tedana workflow and selcomps

### PR DESCRIPTION
**Pull request by tsalo**
Changes proposed in this pull request:

- Remove unused `F_S0_maps` variable from selcomps. My bad!
- Add version switch (with version set by constant `METHOD`) for calling selcomps in tedana workflow.
- Remove calls to `utils.andb` in selcomps. The same things can be accomplished with `&` and `|`, and `andb` is a bit of a misnomer because it returns the sum, which can be used to perform either and or or, but is less readable and requires that you hardcode in the number of arrays you're comparing.
- Explicitly check shapes of mmix and seldict.

### CODE REVIEW

**Comment by tsalo** [comment]
BTW I meant "selcomps", not "welcomes". I hate autocorrect sometimes.

**Comment by tsalo** [comment]
Before you merge this, I want to make extra-double sure that the hardcoded 3 below isn't in reference to the number of echoes:

https://github.com/emdupre/tedana/blob/d76a45a6bf120de3e70d02e0f4ff39bbbcac7afb/tedana/selection/select_comps.py#L179-L182

Do you understand that section?

**Comment by emdupre** [comment]
I'm reading this with quite a bit of jet lag, so apologies if this is a stupid question, but why is that a for-loop at all ? I don't see the indexing variable used anywhere in that statement ?

**Comment by tsalo** [comment]
It's reducing `ncls` (wish I knew what the name meant so I could come up with a better one). I think it finds the index of `ncls` where the increase in variance explained is less than the upper-bound threshold? And yet it also ignores the first one in each iteration of the loop. 

So if the variance explained by the component `ncls[nn]` minus that of `ncls[nn-1]` is less than the upper bound on variance explained, then `ncls[nn]` is kept. Of course, since this is repeated three times, then in the next iteration `ncls[nn]` might now be kept if the new `ncls[nn-1]` is different...

**Comment by emdupre** [comment]
It's actually not indexing `ncls[nn]` at all, as far as I can tell.. It is, though, overwriting each time and using the updated values as inputs -- why it's doing this exactly three times I'm really not sure. I think this is something we'll have to bring up in the eventual commenting and refactoring. Do you think you could note in a comment that we should revisit this point in particular ?

**Comment by tsalo** [comment]
Sorry, you're totally right about the indexing. I should have used something like `i` to reflect that.

I'll add a note to revisit now.

**Comment by emdupre** [comment]
Thank you !! Sorry for being so slow on taking your point. This LGTM ! Merging :tada:

**Pull request merged**
